version: "3.7"

services:
  parity:
    build:
      context: ./parity
    volumes:
      - parity:/parity/data

  nginx:
    build:
      context: ./auth
    depends_on:
      - parity
    ports:
      - 80:80

volumes:
  parity:
