version: "3.7"

services:
  eth:
    build:
      context: ./eth
    volumes:
      - eth:/root
    restart: unless-stopped

  nginx:
    build:
      context: ./auth
    depends_on:
      - eth
    ports:
      - 80:80

volumes:
  eth:
